language: python
python:
  - "2.7"
cache: pip
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - python setup.py install && python -m pytest
after_success:
  - coveralls
branches:
  only:
    - master
