language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - python setup.py install && python -m pytest
branches:
  only:
    - master
