language: python
python:
  - "2.7"
cache: pip
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
before_install:
#  - pip install pytest pytest-cov
#  - pip install coveralls
  - pip install -r test-requirements.txt
install:
  - pip install -r requirements.txt
script:
  - python -m pytest --cov . --cov-report term-missing
after_success:
  - coveralls
branches:
  only:
    - master
